// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package se.locutus.sea_chauffeur;

public final class Messages {
  private Messages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code ResponseCode}
   */
  public enum ResponseCode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>UKNOWN = 0;</code>
     */
    UKNOWN(0),
    /**
     * <code>OK = 1;</code>
     */
    OK(1),
    ;

    /**
     * <code>UKNOWN = 0;</code>
     */
    public static final int UKNOWN_VALUE = 0;
    /**
     * <code>OK = 1;</code>
     */
    public static final int OK_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResponseCode valueOf(int value) {
      return forNumber(value);
    }

    public static ResponseCode forNumber(int value) {
      switch (value) {
        case 0: return UKNOWN;
        case 1: return OK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResponseCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResponseCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResponseCode>() {
            public ResponseCode findValueByNumber(int number) {
              return ResponseCode.forNumber(number);
            }
          };

    private final int value;

    private ResponseCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResponseCode)
  }

  public interface SeaRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SeaRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .NavRequest nav_request = 1;</code>
     */
    boolean hasNavRequest();
    /**
     * <code>optional .NavRequest nav_request = 1;</code>
     */
    se.locutus.sea_chauffeur.Messages.NavRequest getNavRequest();

    /**
     * <code>optional .Configuration update_configuration = 2;</code>
     */
    boolean hasUpdateConfiguration();
    /**
     * <code>optional .Configuration update_configuration = 2;</code>
     */
    se.locutus.sea_chauffeur.Messages.Configuration getUpdateConfiguration();
  }
  /**
   * Protobuf type {@code SeaRequest}
   */
  public  static final class SeaRequest extends
      com.google.protobuf.GeneratedMessageLite<
          SeaRequest, SeaRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:SeaRequest)
      SeaRequestOrBuilder {
    private SeaRequest() {
    }
    private int bitField0_;
    public static final int NAV_REQUEST_FIELD_NUMBER = 1;
    private se.locutus.sea_chauffeur.Messages.NavRequest navRequest_;
    /**
     * <code>optional .NavRequest nav_request = 1;</code>
     */
    public boolean hasNavRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .NavRequest nav_request = 1;</code>
     */
    public se.locutus.sea_chauffeur.Messages.NavRequest getNavRequest() {
      return navRequest_ == null ? se.locutus.sea_chauffeur.Messages.NavRequest.getDefaultInstance() : navRequest_;
    }
    /**
     * <code>optional .NavRequest nav_request = 1;</code>
     */
    private void setNavRequest(se.locutus.sea_chauffeur.Messages.NavRequest value) {
      if (value == null) {
        throw new NullPointerException();
      }
      navRequest_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>optional .NavRequest nav_request = 1;</code>
     */
    private void setNavRequest(
        se.locutus.sea_chauffeur.Messages.NavRequest.Builder builderForValue) {
      navRequest_ = builderForValue.build();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>optional .NavRequest nav_request = 1;</code>
     */
    private void mergeNavRequest(se.locutus.sea_chauffeur.Messages.NavRequest value) {
      if (navRequest_ != null &&
          navRequest_ != se.locutus.sea_chauffeur.Messages.NavRequest.getDefaultInstance()) {
        navRequest_ =
          se.locutus.sea_chauffeur.Messages.NavRequest.newBuilder(navRequest_).mergeFrom(value).buildPartial();
      } else {
        navRequest_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>optional .NavRequest nav_request = 1;</code>
     */
    private void clearNavRequest() {  navRequest_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public static final int UPDATE_CONFIGURATION_FIELD_NUMBER = 2;
    private se.locutus.sea_chauffeur.Messages.Configuration updateConfiguration_;
    /**
     * <code>optional .Configuration update_configuration = 2;</code>
     */
    public boolean hasUpdateConfiguration() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Configuration update_configuration = 2;</code>
     */
    public se.locutus.sea_chauffeur.Messages.Configuration getUpdateConfiguration() {
      return updateConfiguration_ == null ? se.locutus.sea_chauffeur.Messages.Configuration.getDefaultInstance() : updateConfiguration_;
    }
    /**
     * <code>optional .Configuration update_configuration = 2;</code>
     */
    private void setUpdateConfiguration(se.locutus.sea_chauffeur.Messages.Configuration value) {
      if (value == null) {
        throw new NullPointerException();
      }
      updateConfiguration_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <code>optional .Configuration update_configuration = 2;</code>
     */
    private void setUpdateConfiguration(
        se.locutus.sea_chauffeur.Messages.Configuration.Builder builderForValue) {
      updateConfiguration_ = builderForValue.build();
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>optional .Configuration update_configuration = 2;</code>
     */
    private void mergeUpdateConfiguration(se.locutus.sea_chauffeur.Messages.Configuration value) {
      if (updateConfiguration_ != null &&
          updateConfiguration_ != se.locutus.sea_chauffeur.Messages.Configuration.getDefaultInstance()) {
        updateConfiguration_ =
          se.locutus.sea_chauffeur.Messages.Configuration.newBuilder(updateConfiguration_).mergeFrom(value).buildPartial();
      } else {
        updateConfiguration_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>optional .Configuration update_configuration = 2;</code>
     */
    private void clearUpdateConfiguration() {  updateConfiguration_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getNavRequest());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getUpdateConfiguration());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getNavRequest());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getUpdateConfiguration());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static se.locutus.sea_chauffeur.Messages.SeaRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(se.locutus.sea_chauffeur.Messages.SeaRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code SeaRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          se.locutus.sea_chauffeur.Messages.SeaRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:SeaRequest)
        se.locutus.sea_chauffeur.Messages.SeaRequestOrBuilder {
      // Construct using se.locutus.sea_chauffeur.Messages.SeaRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .NavRequest nav_request = 1;</code>
       */
      public boolean hasNavRequest() {
        return instance.hasNavRequest();
      }
      /**
       * <code>optional .NavRequest nav_request = 1;</code>
       */
      public se.locutus.sea_chauffeur.Messages.NavRequest getNavRequest() {
        return instance.getNavRequest();
      }
      /**
       * <code>optional .NavRequest nav_request = 1;</code>
       */
      public Builder setNavRequest(se.locutus.sea_chauffeur.Messages.NavRequest value) {
        copyOnWrite();
        instance.setNavRequest(value);
        return this;
        }
      /**
       * <code>optional .NavRequest nav_request = 1;</code>
       */
      public Builder setNavRequest(
          se.locutus.sea_chauffeur.Messages.NavRequest.Builder builderForValue) {
        copyOnWrite();
        instance.setNavRequest(builderForValue);
        return this;
      }
      /**
       * <code>optional .NavRequest nav_request = 1;</code>
       */
      public Builder mergeNavRequest(se.locutus.sea_chauffeur.Messages.NavRequest value) {
        copyOnWrite();
        instance.mergeNavRequest(value);
        return this;
      }
      /**
       * <code>optional .NavRequest nav_request = 1;</code>
       */
      public Builder clearNavRequest() {  copyOnWrite();
        instance.clearNavRequest();
        return this;
      }

      /**
       * <code>optional .Configuration update_configuration = 2;</code>
       */
      public boolean hasUpdateConfiguration() {
        return instance.hasUpdateConfiguration();
      }
      /**
       * <code>optional .Configuration update_configuration = 2;</code>
       */
      public se.locutus.sea_chauffeur.Messages.Configuration getUpdateConfiguration() {
        return instance.getUpdateConfiguration();
      }
      /**
       * <code>optional .Configuration update_configuration = 2;</code>
       */
      public Builder setUpdateConfiguration(se.locutus.sea_chauffeur.Messages.Configuration value) {
        copyOnWrite();
        instance.setUpdateConfiguration(value);
        return this;
        }
      /**
       * <code>optional .Configuration update_configuration = 2;</code>
       */
      public Builder setUpdateConfiguration(
          se.locutus.sea_chauffeur.Messages.Configuration.Builder builderForValue) {
        copyOnWrite();
        instance.setUpdateConfiguration(builderForValue);
        return this;
      }
      /**
       * <code>optional .Configuration update_configuration = 2;</code>
       */
      public Builder mergeUpdateConfiguration(se.locutus.sea_chauffeur.Messages.Configuration value) {
        copyOnWrite();
        instance.mergeUpdateConfiguration(value);
        return this;
      }
      /**
       * <code>optional .Configuration update_configuration = 2;</code>
       */
      public Builder clearUpdateConfiguration() {  copyOnWrite();
        instance.clearUpdateConfiguration();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SeaRequest)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new se.locutus.sea_chauffeur.Messages.SeaRequest();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (hasNavRequest()) {
            if (!getNavRequest().isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          se.locutus.sea_chauffeur.Messages.SeaRequest other = (se.locutus.sea_chauffeur.Messages.SeaRequest) arg1;
          navRequest_ = visitor.visitMessage(navRequest_, other.navRequest_);
          updateConfiguration_ = visitor.visitMessage(updateConfiguration_, other.updateConfiguration_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  se.locutus.sea_chauffeur.Messages.NavRequest.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    subBuilder = navRequest_.toBuilder();
                  }
                  navRequest_ = input.readMessage(se.locutus.sea_chauffeur.Messages.NavRequest.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(navRequest_);
                    navRequest_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000001;
                  break;
                }
                case 18: {
                  se.locutus.sea_chauffeur.Messages.Configuration.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    subBuilder = updateConfiguration_.toBuilder();
                  }
                  updateConfiguration_ = input.readMessage(se.locutus.sea_chauffeur.Messages.Configuration.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(updateConfiguration_);
                    updateConfiguration_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000002;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (se.locutus.sea_chauffeur.Messages.SeaRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SeaRequest)
    private static final se.locutus.sea_chauffeur.Messages.SeaRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SeaRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static se.locutus.sea_chauffeur.Messages.SeaRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SeaRequest> PARSER;

    public static com.google.protobuf.Parser<SeaRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SeaResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SeaResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required .ResponseCode response_code = 1;</code>
     */
    boolean hasResponseCode();
    /**
     * <code>required .ResponseCode response_code = 1;</code>
     */
    se.locutus.sea_chauffeur.Messages.ResponseCode getResponseCode();

    /**
     * <code>optional .Location current_location = 2;</code>
     */
    boolean hasCurrentLocation();
    /**
     * <code>optional .Location current_location = 2;</code>
     */
    se.locutus.sea_chauffeur.Messages.Location getCurrentLocation();

    /**
     * <code>required .Location current_destination = 3;</code>
     */
    boolean hasCurrentDestination();
    /**
     * <code>required .Location current_destination = 3;</code>
     */
    se.locutus.sea_chauffeur.Messages.Location getCurrentDestination();
  }
  /**
   * Protobuf type {@code SeaResponse}
   */
  public  static final class SeaResponse extends
      com.google.protobuf.GeneratedMessageLite<
          SeaResponse, SeaResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:SeaResponse)
      SeaResponseOrBuilder {
    private SeaResponse() {
    }
    private int bitField0_;
    public static final int RESPONSE_CODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <code>required .ResponseCode response_code = 1;</code>
     */
    public boolean hasResponseCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .ResponseCode response_code = 1;</code>
     */
    public se.locutus.sea_chauffeur.Messages.ResponseCode getResponseCode() {
      se.locutus.sea_chauffeur.Messages.ResponseCode result = se.locutus.sea_chauffeur.Messages.ResponseCode.forNumber(responseCode_);
      return result == null ? se.locutus.sea_chauffeur.Messages.ResponseCode.UKNOWN : result;
    }
    /**
     * <code>required .ResponseCode response_code = 1;</code>
     */
    private void setResponseCode(se.locutus.sea_chauffeur.Messages.ResponseCode value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      responseCode_ = value.getNumber();
    }
    /**
     * <code>required .ResponseCode response_code = 1;</code>
     */
    private void clearResponseCode() {
      bitField0_ = (bitField0_ & ~0x00000001);
      responseCode_ = 0;
    }

    public static final int CURRENT_LOCATION_FIELD_NUMBER = 2;
    private se.locutus.sea_chauffeur.Messages.Location currentLocation_;
    /**
     * <code>optional .Location current_location = 2;</code>
     */
    public boolean hasCurrentLocation() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .Location current_location = 2;</code>
     */
    public se.locutus.sea_chauffeur.Messages.Location getCurrentLocation() {
      return currentLocation_ == null ? se.locutus.sea_chauffeur.Messages.Location.getDefaultInstance() : currentLocation_;
    }
    /**
     * <code>optional .Location current_location = 2;</code>
     */
    private void setCurrentLocation(se.locutus.sea_chauffeur.Messages.Location value) {
      if (value == null) {
        throw new NullPointerException();
      }
      currentLocation_ = value;
      bitField0_ |= 0x00000002;
      }
    /**
     * <code>optional .Location current_location = 2;</code>
     */
    private void setCurrentLocation(
        se.locutus.sea_chauffeur.Messages.Location.Builder builderForValue) {
      currentLocation_ = builderForValue.build();
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>optional .Location current_location = 2;</code>
     */
    private void mergeCurrentLocation(se.locutus.sea_chauffeur.Messages.Location value) {
      if (currentLocation_ != null &&
          currentLocation_ != se.locutus.sea_chauffeur.Messages.Location.getDefaultInstance()) {
        currentLocation_ =
          se.locutus.sea_chauffeur.Messages.Location.newBuilder(currentLocation_).mergeFrom(value).buildPartial();
      } else {
        currentLocation_ = value;
      }
      bitField0_ |= 0x00000002;
    }
    /**
     * <code>optional .Location current_location = 2;</code>
     */
    private void clearCurrentLocation() {  currentLocation_ = null;
      bitField0_ = (bitField0_ & ~0x00000002);
    }

    public static final int CURRENT_DESTINATION_FIELD_NUMBER = 3;
    private se.locutus.sea_chauffeur.Messages.Location currentDestination_;
    /**
     * <code>required .Location current_destination = 3;</code>
     */
    public boolean hasCurrentDestination() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .Location current_destination = 3;</code>
     */
    public se.locutus.sea_chauffeur.Messages.Location getCurrentDestination() {
      return currentDestination_ == null ? se.locutus.sea_chauffeur.Messages.Location.getDefaultInstance() : currentDestination_;
    }
    /**
     * <code>required .Location current_destination = 3;</code>
     */
    private void setCurrentDestination(se.locutus.sea_chauffeur.Messages.Location value) {
      if (value == null) {
        throw new NullPointerException();
      }
      currentDestination_ = value;
      bitField0_ |= 0x00000004;
      }
    /**
     * <code>required .Location current_destination = 3;</code>
     */
    private void setCurrentDestination(
        se.locutus.sea_chauffeur.Messages.Location.Builder builderForValue) {
      currentDestination_ = builderForValue.build();
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>required .Location current_destination = 3;</code>
     */
    private void mergeCurrentDestination(se.locutus.sea_chauffeur.Messages.Location value) {
      if (currentDestination_ != null &&
          currentDestination_ != se.locutus.sea_chauffeur.Messages.Location.getDefaultInstance()) {
        currentDestination_ =
          se.locutus.sea_chauffeur.Messages.Location.newBuilder(currentDestination_).mergeFrom(value).buildPartial();
      } else {
        currentDestination_ = value;
      }
      bitField0_ |= 0x00000004;
    }
    /**
     * <code>required .Location current_destination = 3;</code>
     */
    private void clearCurrentDestination() {  currentDestination_ = null;
      bitField0_ = (bitField0_ & ~0x00000004);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, responseCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getCurrentLocation());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getCurrentDestination());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, responseCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getCurrentLocation());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getCurrentDestination());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static se.locutus.sea_chauffeur.Messages.SeaResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.SeaResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(se.locutus.sea_chauffeur.Messages.SeaResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code SeaResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          se.locutus.sea_chauffeur.Messages.SeaResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:SeaResponse)
        se.locutus.sea_chauffeur.Messages.SeaResponseOrBuilder {
      // Construct using se.locutus.sea_chauffeur.Messages.SeaResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required .ResponseCode response_code = 1;</code>
       */
      public boolean hasResponseCode() {
        return instance.hasResponseCode();
      }
      /**
       * <code>required .ResponseCode response_code = 1;</code>
       */
      public se.locutus.sea_chauffeur.Messages.ResponseCode getResponseCode() {
        return instance.getResponseCode();
      }
      /**
       * <code>required .ResponseCode response_code = 1;</code>
       */
      public Builder setResponseCode(se.locutus.sea_chauffeur.Messages.ResponseCode value) {
        copyOnWrite();
        instance.setResponseCode(value);
        return this;
      }
      /**
       * <code>required .ResponseCode response_code = 1;</code>
       */
      public Builder clearResponseCode() {
        copyOnWrite();
        instance.clearResponseCode();
        return this;
      }

      /**
       * <code>optional .Location current_location = 2;</code>
       */
      public boolean hasCurrentLocation() {
        return instance.hasCurrentLocation();
      }
      /**
       * <code>optional .Location current_location = 2;</code>
       */
      public se.locutus.sea_chauffeur.Messages.Location getCurrentLocation() {
        return instance.getCurrentLocation();
      }
      /**
       * <code>optional .Location current_location = 2;</code>
       */
      public Builder setCurrentLocation(se.locutus.sea_chauffeur.Messages.Location value) {
        copyOnWrite();
        instance.setCurrentLocation(value);
        return this;
        }
      /**
       * <code>optional .Location current_location = 2;</code>
       */
      public Builder setCurrentLocation(
          se.locutus.sea_chauffeur.Messages.Location.Builder builderForValue) {
        copyOnWrite();
        instance.setCurrentLocation(builderForValue);
        return this;
      }
      /**
       * <code>optional .Location current_location = 2;</code>
       */
      public Builder mergeCurrentLocation(se.locutus.sea_chauffeur.Messages.Location value) {
        copyOnWrite();
        instance.mergeCurrentLocation(value);
        return this;
      }
      /**
       * <code>optional .Location current_location = 2;</code>
       */
      public Builder clearCurrentLocation() {  copyOnWrite();
        instance.clearCurrentLocation();
        return this;
      }

      /**
       * <code>required .Location current_destination = 3;</code>
       */
      public boolean hasCurrentDestination() {
        return instance.hasCurrentDestination();
      }
      /**
       * <code>required .Location current_destination = 3;</code>
       */
      public se.locutus.sea_chauffeur.Messages.Location getCurrentDestination() {
        return instance.getCurrentDestination();
      }
      /**
       * <code>required .Location current_destination = 3;</code>
       */
      public Builder setCurrentDestination(se.locutus.sea_chauffeur.Messages.Location value) {
        copyOnWrite();
        instance.setCurrentDestination(value);
        return this;
        }
      /**
       * <code>required .Location current_destination = 3;</code>
       */
      public Builder setCurrentDestination(
          se.locutus.sea_chauffeur.Messages.Location.Builder builderForValue) {
        copyOnWrite();
        instance.setCurrentDestination(builderForValue);
        return this;
      }
      /**
       * <code>required .Location current_destination = 3;</code>
       */
      public Builder mergeCurrentDestination(se.locutus.sea_chauffeur.Messages.Location value) {
        copyOnWrite();
        instance.mergeCurrentDestination(value);
        return this;
      }
      /**
       * <code>required .Location current_destination = 3;</code>
       */
      public Builder clearCurrentDestination() {  copyOnWrite();
        instance.clearCurrentDestination();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:SeaResponse)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new se.locutus.sea_chauffeur.Messages.SeaResponse();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasResponseCode()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasCurrentDestination()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (hasCurrentLocation()) {
            if (!getCurrentLocation().isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (!getCurrentDestination().isInitialized()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          se.locutus.sea_chauffeur.Messages.SeaResponse other = (se.locutus.sea_chauffeur.Messages.SeaResponse) arg1;
          responseCode_ = visitor.visitInt(hasResponseCode(), responseCode_,
              other.hasResponseCode(), other.responseCode_);
          currentLocation_ = visitor.visitMessage(currentLocation_, other.currentLocation_);
          currentDestination_ = visitor.visitMessage(currentDestination_, other.currentDestination_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  int rawValue = input.readEnum();
                  se.locutus.sea_chauffeur.Messages.ResponseCode value = se.locutus.sea_chauffeur.Messages.ResponseCode.forNumber(rawValue);
                  if (value == null) {
                    super.mergeVarintField(1, rawValue);
                  } else {
                    bitField0_ |= 0x00000001;
                    responseCode_ = rawValue;
                  }
                  break;
                }
                case 18: {
                  se.locutus.sea_chauffeur.Messages.Location.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000002) == 0x00000002)) {
                    subBuilder = currentLocation_.toBuilder();
                  }
                  currentLocation_ = input.readMessage(se.locutus.sea_chauffeur.Messages.Location.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(currentLocation_);
                    currentLocation_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000002;
                  break;
                }
                case 26: {
                  se.locutus.sea_chauffeur.Messages.Location.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000004) == 0x00000004)) {
                    subBuilder = currentDestination_.toBuilder();
                  }
                  currentDestination_ = input.readMessage(se.locutus.sea_chauffeur.Messages.Location.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(currentDestination_);
                    currentDestination_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000004;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (se.locutus.sea_chauffeur.Messages.SeaResponse.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:SeaResponse)
    private static final se.locutus.sea_chauffeur.Messages.SeaResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SeaResponse();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static se.locutus.sea_chauffeur.Messages.SeaResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SeaResponse> PARSER;

    public static com.google.protobuf.Parser<SeaResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface NavRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NavRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional .Location location = 1;</code>
     */
    boolean hasLocation();
    /**
     * <code>optional .Location location = 1;</code>
     */
    se.locutus.sea_chauffeur.Messages.Location getLocation();
  }
  /**
   * Protobuf type {@code NavRequest}
   */
  public  static final class NavRequest extends
      com.google.protobuf.GeneratedMessageLite<
          NavRequest, NavRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:NavRequest)
      NavRequestOrBuilder {
    private NavRequest() {
    }
    private int bitField0_;
    public static final int LOCATION_FIELD_NUMBER = 1;
    private se.locutus.sea_chauffeur.Messages.Location location_;
    /**
     * <code>optional .Location location = 1;</code>
     */
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .Location location = 1;</code>
     */
    public se.locutus.sea_chauffeur.Messages.Location getLocation() {
      return location_ == null ? se.locutus.sea_chauffeur.Messages.Location.getDefaultInstance() : location_;
    }
    /**
     * <code>optional .Location location = 1;</code>
     */
    private void setLocation(se.locutus.sea_chauffeur.Messages.Location value) {
      if (value == null) {
        throw new NullPointerException();
      }
      location_ = value;
      bitField0_ |= 0x00000001;
      }
    /**
     * <code>optional .Location location = 1;</code>
     */
    private void setLocation(
        se.locutus.sea_chauffeur.Messages.Location.Builder builderForValue) {
      location_ = builderForValue.build();
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>optional .Location location = 1;</code>
     */
    private void mergeLocation(se.locutus.sea_chauffeur.Messages.Location value) {
      if (location_ != null &&
          location_ != se.locutus.sea_chauffeur.Messages.Location.getDefaultInstance()) {
        location_ =
          se.locutus.sea_chauffeur.Messages.Location.newBuilder(location_).mergeFrom(value).buildPartial();
      } else {
        location_ = value;
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <code>optional .Location location = 1;</code>
     */
    private void clearLocation() {  location_ = null;
      bitField0_ = (bitField0_ & ~0x00000001);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, getLocation());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getLocation());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static se.locutus.sea_chauffeur.Messages.NavRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.locutus.sea_chauffeur.Messages.NavRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.NavRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.locutus.sea_chauffeur.Messages.NavRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.NavRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.NavRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.NavRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.NavRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.NavRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.NavRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(se.locutus.sea_chauffeur.Messages.NavRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code NavRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          se.locutus.sea_chauffeur.Messages.NavRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:NavRequest)
        se.locutus.sea_chauffeur.Messages.NavRequestOrBuilder {
      // Construct using se.locutus.sea_chauffeur.Messages.NavRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional .Location location = 1;</code>
       */
      public boolean hasLocation() {
        return instance.hasLocation();
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public se.locutus.sea_chauffeur.Messages.Location getLocation() {
        return instance.getLocation();
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public Builder setLocation(se.locutus.sea_chauffeur.Messages.Location value) {
        copyOnWrite();
        instance.setLocation(value);
        return this;
        }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public Builder setLocation(
          se.locutus.sea_chauffeur.Messages.Location.Builder builderForValue) {
        copyOnWrite();
        instance.setLocation(builderForValue);
        return this;
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public Builder mergeLocation(se.locutus.sea_chauffeur.Messages.Location value) {
        copyOnWrite();
        instance.mergeLocation(value);
        return this;
      }
      /**
       * <code>optional .Location location = 1;</code>
       */
      public Builder clearLocation() {  copyOnWrite();
        instance.clearLocation();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NavRequest)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new se.locutus.sea_chauffeur.Messages.NavRequest();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (hasLocation()) {
            if (!getLocation().isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          se.locutus.sea_chauffeur.Messages.NavRequest other = (se.locutus.sea_chauffeur.Messages.NavRequest) arg1;
          location_ = visitor.visitMessage(location_, other.location_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  se.locutus.sea_chauffeur.Messages.Location.Builder subBuilder = null;
                  if (((bitField0_ & 0x00000001) == 0x00000001)) {
                    subBuilder = location_.toBuilder();
                  }
                  location_ = input.readMessage(se.locutus.sea_chauffeur.Messages.Location.parser(), extensionRegistry);
                  if (subBuilder != null) {
                    subBuilder.mergeFrom(location_);
                    location_ = subBuilder.buildPartial();
                  }
                  bitField0_ |= 0x00000001;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (se.locutus.sea_chauffeur.Messages.NavRequest.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:NavRequest)
    private static final se.locutus.sea_chauffeur.Messages.NavRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new NavRequest();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static se.locutus.sea_chauffeur.Messages.NavRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<NavRequest> PARSER;

    public static com.google.protobuf.Parser<NavRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Location)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required float lat = 1;</code>
     */
    boolean hasLat();
    /**
     * <code>required float lat = 1;</code>
     */
    float getLat();

    /**
     * <code>required float lng = 2;</code>
     */
    boolean hasLng();
    /**
     * <code>required float lng = 2;</code>
     */
    float getLng();
  }
  /**
   * Protobuf type {@code Location}
   */
  public  static final class Location extends
      com.google.protobuf.GeneratedMessageLite<
          Location, Location.Builder> implements
      // @@protoc_insertion_point(message_implements:Location)
      LocationOrBuilder {
    private Location() {
    }
    private int bitField0_;
    public static final int LAT_FIELD_NUMBER = 1;
    private float lat_;
    /**
     * <code>required float lat = 1;</code>
     */
    public boolean hasLat() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required float lat = 1;</code>
     */
    public float getLat() {
      return lat_;
    }
    /**
     * <code>required float lat = 1;</code>
     */
    private void setLat(float value) {
      bitField0_ |= 0x00000001;
      lat_ = value;
    }
    /**
     * <code>required float lat = 1;</code>
     */
    private void clearLat() {
      bitField0_ = (bitField0_ & ~0x00000001);
      lat_ = 0F;
    }

    public static final int LNG_FIELD_NUMBER = 2;
    private float lng_;
    /**
     * <code>required float lng = 2;</code>
     */
    public boolean hasLng() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float lng = 2;</code>
     */
    public float getLng() {
      return lng_;
    }
    /**
     * <code>required float lng = 2;</code>
     */
    private void setLng(float value) {
      bitField0_ |= 0x00000002;
      lng_ = value;
    }
    /**
     * <code>required float lng = 2;</code>
     */
    private void clearLng() {
      bitField0_ = (bitField0_ & ~0x00000002);
      lng_ = 0F;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, lng_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, lat_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, lng_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static se.locutus.sea_chauffeur.Messages.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.locutus.sea_chauffeur.Messages.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.locutus.sea_chauffeur.Messages.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(se.locutus.sea_chauffeur.Messages.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          se.locutus.sea_chauffeur.Messages.Location, Builder> implements
        // @@protoc_insertion_point(builder_implements:Location)
        se.locutus.sea_chauffeur.Messages.LocationOrBuilder {
      // Construct using se.locutus.sea_chauffeur.Messages.Location.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required float lat = 1;</code>
       */
      public boolean hasLat() {
        return instance.hasLat();
      }
      /**
       * <code>required float lat = 1;</code>
       */
      public float getLat() {
        return instance.getLat();
      }
      /**
       * <code>required float lat = 1;</code>
       */
      public Builder setLat(float value) {
        copyOnWrite();
        instance.setLat(value);
        return this;
      }
      /**
       * <code>required float lat = 1;</code>
       */
      public Builder clearLat() {
        copyOnWrite();
        instance.clearLat();
        return this;
      }

      /**
       * <code>required float lng = 2;</code>
       */
      public boolean hasLng() {
        return instance.hasLng();
      }
      /**
       * <code>required float lng = 2;</code>
       */
      public float getLng() {
        return instance.getLng();
      }
      /**
       * <code>required float lng = 2;</code>
       */
      public Builder setLng(float value) {
        copyOnWrite();
        instance.setLng(value);
        return this;
      }
      /**
       * <code>required float lng = 2;</code>
       */
      public Builder clearLng() {
        copyOnWrite();
        instance.clearLng();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Location)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new se.locutus.sea_chauffeur.Messages.Location();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasLat()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasLng()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          se.locutus.sea_chauffeur.Messages.Location other = (se.locutus.sea_chauffeur.Messages.Location) arg1;
          lat_ = visitor.visitFloat(
              hasLat(), lat_,
              other.hasLat(), other.lat_);
          lng_ = visitor.visitFloat(
              hasLng(), lng_,
              other.hasLng(), other.lng_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 13: {
                  bitField0_ |= 0x00000001;
                  lat_ = input.readFloat();
                  break;
                }
                case 21: {
                  bitField0_ |= 0x00000002;
                  lng_ = input.readFloat();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (se.locutus.sea_chauffeur.Messages.Location.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Location)
    private static final se.locutus.sea_chauffeur.Messages.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Location();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static se.locutus.sea_chauffeur.Messages.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Location> PARSER;

    public static com.google.protobuf.Parser<Location> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ConfigurationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Configuration)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional uint32 millis_duration_per_degree_second = 1 [default = 30];</code>
     */
    boolean hasMillisDurationPerDegreeSecond();
    /**
     * <code>optional uint32 millis_duration_per_degree_second = 1 [default = 30];</code>
     */
    int getMillisDurationPerDegreeSecond();

    /**
     * <pre>
     * Power settings for motor in slow nudge.
     * </pre>
     *
     * <code>optional uint32 power_low_mode = 2 [default = 100];</code>
     */
    boolean hasPowerLowMode();
    /**
     * <pre>
     * Power settings for motor in slow nudge.
     * </pre>
     *
     * <code>optional uint32 power_low_mode = 2 [default = 100];</code>
     */
    int getPowerLowMode();

    /**
     * <pre>
     * Power settings for motor in medium nudge.
     * </pre>
     *
     * <code>optional uint32 power_medium_mode = 3 [default = 200];</code>
     */
    boolean hasPowerMediumMode();
    /**
     * <pre>
     * Power settings for motor in medium nudge.
     * </pre>
     *
     * <code>optional uint32 power_medium_mode = 3 [default = 200];</code>
     */
    int getPowerMediumMode();

    /**
     * <code>optional float knots_to_lock_course = 4 [default = 1];</code>
     */
    boolean hasKnotsToLockCourse();
    /**
     * <code>optional float knots_to_lock_course = 4 [default = 1];</code>
     */
    float getKnotsToLockCourse();
  }
  /**
   * Protobuf type {@code Configuration}
   */
  public  static final class Configuration extends
      com.google.protobuf.GeneratedMessageLite<
          Configuration, Configuration.Builder> implements
      // @@protoc_insertion_point(message_implements:Configuration)
      ConfigurationOrBuilder {
    private Configuration() {
      millisDurationPerDegreeSecond_ = 30;
      powerLowMode_ = 100;
      powerMediumMode_ = 200;
      knotsToLockCourse_ = 1F;
    }
    private int bitField0_;
    public static final int MILLIS_DURATION_PER_DEGREE_SECOND_FIELD_NUMBER = 1;
    private int millisDurationPerDegreeSecond_;
    /**
     * <code>optional uint32 millis_duration_per_degree_second = 1 [default = 30];</code>
     */
    public boolean hasMillisDurationPerDegreeSecond() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 millis_duration_per_degree_second = 1 [default = 30];</code>
     */
    public int getMillisDurationPerDegreeSecond() {
      return millisDurationPerDegreeSecond_;
    }
    /**
     * <code>optional uint32 millis_duration_per_degree_second = 1 [default = 30];</code>
     */
    private void setMillisDurationPerDegreeSecond(int value) {
      bitField0_ |= 0x00000001;
      millisDurationPerDegreeSecond_ = value;
    }
    /**
     * <code>optional uint32 millis_duration_per_degree_second = 1 [default = 30];</code>
     */
    private void clearMillisDurationPerDegreeSecond() {
      bitField0_ = (bitField0_ & ~0x00000001);
      millisDurationPerDegreeSecond_ = 30;
    }

    public static final int POWER_LOW_MODE_FIELD_NUMBER = 2;
    private int powerLowMode_;
    /**
     * <pre>
     * Power settings for motor in slow nudge.
     * </pre>
     *
     * <code>optional uint32 power_low_mode = 2 [default = 100];</code>
     */
    public boolean hasPowerLowMode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * Power settings for motor in slow nudge.
     * </pre>
     *
     * <code>optional uint32 power_low_mode = 2 [default = 100];</code>
     */
    public int getPowerLowMode() {
      return powerLowMode_;
    }
    /**
     * <pre>
     * Power settings for motor in slow nudge.
     * </pre>
     *
     * <code>optional uint32 power_low_mode = 2 [default = 100];</code>
     */
    private void setPowerLowMode(int value) {
      bitField0_ |= 0x00000002;
      powerLowMode_ = value;
    }
    /**
     * <pre>
     * Power settings for motor in slow nudge.
     * </pre>
     *
     * <code>optional uint32 power_low_mode = 2 [default = 100];</code>
     */
    private void clearPowerLowMode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      powerLowMode_ = 100;
    }

    public static final int POWER_MEDIUM_MODE_FIELD_NUMBER = 3;
    private int powerMediumMode_;
    /**
     * <pre>
     * Power settings for motor in medium nudge.
     * </pre>
     *
     * <code>optional uint32 power_medium_mode = 3 [default = 200];</code>
     */
    public boolean hasPowerMediumMode() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * Power settings for motor in medium nudge.
     * </pre>
     *
     * <code>optional uint32 power_medium_mode = 3 [default = 200];</code>
     */
    public int getPowerMediumMode() {
      return powerMediumMode_;
    }
    /**
     * <pre>
     * Power settings for motor in medium nudge.
     * </pre>
     *
     * <code>optional uint32 power_medium_mode = 3 [default = 200];</code>
     */
    private void setPowerMediumMode(int value) {
      bitField0_ |= 0x00000004;
      powerMediumMode_ = value;
    }
    /**
     * <pre>
     * Power settings for motor in medium nudge.
     * </pre>
     *
     * <code>optional uint32 power_medium_mode = 3 [default = 200];</code>
     */
    private void clearPowerMediumMode() {
      bitField0_ = (bitField0_ & ~0x00000004);
      powerMediumMode_ = 200;
    }

    public static final int KNOTS_TO_LOCK_COURSE_FIELD_NUMBER = 4;
    private float knotsToLockCourse_;
    /**
     * <code>optional float knots_to_lock_course = 4 [default = 1];</code>
     */
    public boolean hasKnotsToLockCourse() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float knots_to_lock_course = 4 [default = 1];</code>
     */
    public float getKnotsToLockCourse() {
      return knotsToLockCourse_;
    }
    /**
     * <code>optional float knots_to_lock_course = 4 [default = 1];</code>
     */
    private void setKnotsToLockCourse(float value) {
      bitField0_ |= 0x00000008;
      knotsToLockCourse_ = value;
    }
    /**
     * <code>optional float knots_to_lock_course = 4 [default = 1];</code>
     */
    private void clearKnotsToLockCourse() {
      bitField0_ = (bitField0_ & ~0x00000008);
      knotsToLockCourse_ = 1F;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, millisDurationPerDegreeSecond_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, powerLowMode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, powerMediumMode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, knotsToLockCourse_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, millisDurationPerDegreeSecond_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, powerLowMode_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, powerMediumMode_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, knotsToLockCourse_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static se.locutus.sea_chauffeur.Messages.Configuration parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.locutus.sea_chauffeur.Messages.Configuration parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.Configuration parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static se.locutus.sea_chauffeur.Messages.Configuration parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.Configuration parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.Configuration parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.Configuration parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.Configuration parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static se.locutus.sea_chauffeur.Messages.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static se.locutus.sea_chauffeur.Messages.Configuration parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(se.locutus.sea_chauffeur.Messages.Configuration prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code Configuration}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          se.locutus.sea_chauffeur.Messages.Configuration, Builder> implements
        // @@protoc_insertion_point(builder_implements:Configuration)
        se.locutus.sea_chauffeur.Messages.ConfigurationOrBuilder {
      // Construct using se.locutus.sea_chauffeur.Messages.Configuration.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>optional uint32 millis_duration_per_degree_second = 1 [default = 30];</code>
       */
      public boolean hasMillisDurationPerDegreeSecond() {
        return instance.hasMillisDurationPerDegreeSecond();
      }
      /**
       * <code>optional uint32 millis_duration_per_degree_second = 1 [default = 30];</code>
       */
      public int getMillisDurationPerDegreeSecond() {
        return instance.getMillisDurationPerDegreeSecond();
      }
      /**
       * <code>optional uint32 millis_duration_per_degree_second = 1 [default = 30];</code>
       */
      public Builder setMillisDurationPerDegreeSecond(int value) {
        copyOnWrite();
        instance.setMillisDurationPerDegreeSecond(value);
        return this;
      }
      /**
       * <code>optional uint32 millis_duration_per_degree_second = 1 [default = 30];</code>
       */
      public Builder clearMillisDurationPerDegreeSecond() {
        copyOnWrite();
        instance.clearMillisDurationPerDegreeSecond();
        return this;
      }

      /**
       * <pre>
       * Power settings for motor in slow nudge.
       * </pre>
       *
       * <code>optional uint32 power_low_mode = 2 [default = 100];</code>
       */
      public boolean hasPowerLowMode() {
        return instance.hasPowerLowMode();
      }
      /**
       * <pre>
       * Power settings for motor in slow nudge.
       * </pre>
       *
       * <code>optional uint32 power_low_mode = 2 [default = 100];</code>
       */
      public int getPowerLowMode() {
        return instance.getPowerLowMode();
      }
      /**
       * <pre>
       * Power settings for motor in slow nudge.
       * </pre>
       *
       * <code>optional uint32 power_low_mode = 2 [default = 100];</code>
       */
      public Builder setPowerLowMode(int value) {
        copyOnWrite();
        instance.setPowerLowMode(value);
        return this;
      }
      /**
       * <pre>
       * Power settings for motor in slow nudge.
       * </pre>
       *
       * <code>optional uint32 power_low_mode = 2 [default = 100];</code>
       */
      public Builder clearPowerLowMode() {
        copyOnWrite();
        instance.clearPowerLowMode();
        return this;
      }

      /**
       * <pre>
       * Power settings for motor in medium nudge.
       * </pre>
       *
       * <code>optional uint32 power_medium_mode = 3 [default = 200];</code>
       */
      public boolean hasPowerMediumMode() {
        return instance.hasPowerMediumMode();
      }
      /**
       * <pre>
       * Power settings for motor in medium nudge.
       * </pre>
       *
       * <code>optional uint32 power_medium_mode = 3 [default = 200];</code>
       */
      public int getPowerMediumMode() {
        return instance.getPowerMediumMode();
      }
      /**
       * <pre>
       * Power settings for motor in medium nudge.
       * </pre>
       *
       * <code>optional uint32 power_medium_mode = 3 [default = 200];</code>
       */
      public Builder setPowerMediumMode(int value) {
        copyOnWrite();
        instance.setPowerMediumMode(value);
        return this;
      }
      /**
       * <pre>
       * Power settings for motor in medium nudge.
       * </pre>
       *
       * <code>optional uint32 power_medium_mode = 3 [default = 200];</code>
       */
      public Builder clearPowerMediumMode() {
        copyOnWrite();
        instance.clearPowerMediumMode();
        return this;
      }

      /**
       * <code>optional float knots_to_lock_course = 4 [default = 1];</code>
       */
      public boolean hasKnotsToLockCourse() {
        return instance.hasKnotsToLockCourse();
      }
      /**
       * <code>optional float knots_to_lock_course = 4 [default = 1];</code>
       */
      public float getKnotsToLockCourse() {
        return instance.getKnotsToLockCourse();
      }
      /**
       * <code>optional float knots_to_lock_course = 4 [default = 1];</code>
       */
      public Builder setKnotsToLockCourse(float value) {
        copyOnWrite();
        instance.setKnotsToLockCourse(value);
        return this;
      }
      /**
       * <code>optional float knots_to_lock_course = 4 [default = 1];</code>
       */
      public Builder clearKnotsToLockCourse() {
        copyOnWrite();
        instance.clearKnotsToLockCourse();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Configuration)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new se.locutus.sea_chauffeur.Messages.Configuration();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          se.locutus.sea_chauffeur.Messages.Configuration other = (se.locutus.sea_chauffeur.Messages.Configuration) arg1;
          millisDurationPerDegreeSecond_ = visitor.visitInt(
              hasMillisDurationPerDegreeSecond(), millisDurationPerDegreeSecond_,
              other.hasMillisDurationPerDegreeSecond(), other.millisDurationPerDegreeSecond_);
          powerLowMode_ = visitor.visitInt(
              hasPowerLowMode(), powerLowMode_,
              other.hasPowerLowMode(), other.powerLowMode_);
          powerMediumMode_ = visitor.visitInt(
              hasPowerMediumMode(), powerMediumMode_,
              other.hasPowerMediumMode(), other.powerMediumMode_);
          knotsToLockCourse_ = visitor.visitFloat(
              hasKnotsToLockCourse(), knotsToLockCourse_,
              other.hasKnotsToLockCourse(), other.knotsToLockCourse_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  millisDurationPerDegreeSecond_ = input.readUInt32();
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  powerLowMode_ = input.readUInt32();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  powerMediumMode_ = input.readUInt32();
                  break;
                }
                case 37: {
                  bitField0_ |= 0x00000008;
                  knotsToLockCourse_ = input.readFloat();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (se.locutus.sea_chauffeur.Messages.Configuration.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:Configuration)
    private static final se.locutus.sea_chauffeur.Messages.Configuration DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Configuration();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static se.locutus.sea_chauffeur.Messages.Configuration getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Configuration> PARSER;

    public static com.google.protobuf.Parser<Configuration> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
