/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Tue Apr 16 21:14:20 2019. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SeaRequest_fields[2] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, SeaRequest, nav_request, nav_request, &NavRequest_fields),
    PB_LAST_FIELD
};

const pb_field_t SeaResponse_fields[2] = {
    PB_FIELD(  1, UENUM   , OPTIONAL, STATIC  , FIRST, SeaResponse, response_code, response_code, 0),
    PB_LAST_FIELD
};

const pb_field_t NavRequest_fields[3] = {
    PB_FIELD(  1, FLOAT   , OPTIONAL, STATIC  , FIRST, NavRequest, lat, lat, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, NavRequest, lng, lat, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SeaRequest, nav_request) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SeaRequest_SeaResponse_NavRequest)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SeaRequest, nav_request) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_SeaRequest_SeaResponse_NavRequest)
#endif


/* @@protoc_insertion_point(eof) */
