/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Wed May 08 12:21:14 2019. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t Configuration_millis_duration_per_degree_second_default = 300u;
const uint32_t Configuration_power_low_mode_default = 100u;
const uint32_t Configuration_power_medium_mode_default = 200u;
const float Configuration_knots_to_lock_course_default = 1;


const pb_field_t SeaRequest_fields[4] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, SeaRequest, nav_request, nav_request, &NavRequest_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, SeaRequest, update_configuration, nav_request, &Configuration_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, SeaRequest, trim_request, update_configuration, &SteeringMove_fields),
    PB_LAST_FIELD
};

const pb_field_t SeaResponse_fields[7] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, SeaResponse, response_code, response_code, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, SeaResponse, current_location, response_code, &Location_fields),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, SeaResponse, current_course, current_location, 0),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, SeaResponse, current_destination, current_course, &Location_fields),
    PB_FIELD(  5, FLOAT   , OPTIONAL, STATIC  , OTHER, SeaResponse, course_to_destination, current_destination, 0),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, SeaResponse, steering_move, course_to_destination, &SteeringMove_fields),
    PB_LAST_FIELD
};

const pb_field_t NavRequest_fields[2] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, NavRequest, location, location, &Location_fields),
    PB_LAST_FIELD
};

const pb_field_t SteeringMove_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, SteeringMove, direction, direction, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, SteeringMove, power, direction, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, SteeringMove, millis, power, 0),
    PB_LAST_FIELD
};

const pb_field_t Location_fields[3] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, Location, lat, lat, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, Location, lng, lat, 0),
    PB_LAST_FIELD
};

const pb_field_t Configuration_fields[5] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, Configuration, millis_duration_per_degree_second, millis_duration_per_degree_second, &Configuration_millis_duration_per_degree_second_default),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, Configuration, power_low_mode, millis_duration_per_degree_second, &Configuration_power_low_mode_default),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, Configuration, power_medium_mode, power_low_mode, &Configuration_power_medium_mode_default),
    PB_FIELD(  4, FLOAT   , OPTIONAL, STATIC  , OTHER, Configuration, knots_to_lock_course, power_medium_mode, &Configuration_knots_to_lock_course_default),
    PB_LAST_FIELD
};




/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SeaRequest, nav_request) < 65536 && pb_membersize(SeaRequest, update_configuration) < 65536 && pb_membersize(SeaRequest, trim_request) < 65536 && pb_membersize(SeaResponse, current_location) < 65536 && pb_membersize(SeaResponse, current_destination) < 65536 && pb_membersize(SeaResponse, steering_move) < 65536 && pb_membersize(NavRequest, location) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_SeaRequest_SeaResponse_NavRequest_SteeringMove_Location_Configuration)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(SeaRequest, nav_request) < 256 && pb_membersize(SeaRequest, update_configuration) < 256 && pb_membersize(SeaRequest, trim_request) < 256 && pb_membersize(SeaResponse, current_location) < 256 && pb_membersize(SeaResponse, current_destination) < 256 && pb_membersize(SeaResponse, steering_move) < 256 && pb_membersize(NavRequest, location) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_SeaRequest_SeaResponse_NavRequest_SteeringMove_Location_Configuration)
#endif


/* @@protoc_insertion_point(eof) */
